### ISSUE TITLE
not working anymore on Xperia X with SailfishOS 3.4

### ISSUE THREAD

**Issue by fuchsmich** [Olf0/crypto-sdcard#29]
* [systemd-escape](https://github.com/Olf0/crypto-sdcard/blob/5d6477ffcf6fcd8d44a9ba4e4a4ce5064479a485/udev/rules.d/96-cryptosd.rules#L2) has been moved to `/usr/bin/systemd-escape`
* [lazymode](https://github.com/Olf0/crypto-sdcard/blob/5d6477ffcf6fcd8d44a9ba4e4a4ce5064479a485/systemd/system/mount-cryptosd-luks%40.service#L20) is not allowed, so I removed it

Now I'm stuck with:

```
systemd[1]: mount-cryptosd-luks@crypto_luks_<UUID>.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Mount LUKS encrypted SD-card (crypto_luks_<UUID>) with udisks.
udisksctl-user[1695]: Error mounting /dev/dm-2: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation
udisksctl-user[1695]: Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address 
```
EDIT: found solution for last problem:
 * As my nemo user wasn't in the group `system` (anymore?) I changed the line in [polkit rule](https://github.com/Olf0/crypto-sdcard/blob/5d6477ffcf6fcd8d44a9ba4e4a4ce5064479a485/polkit-1/localauthority/50-local.d/69-cryptosd.pkla#L2) to
    
        Identity=unix-group:sailfish-system

It's working again now. I have no idea if this is a problem which is specific to my phone or a general problem, coz I found no report about it.

**Comment by Olf0** [comment]
@fuchsmich, thank you for your report.
I am not on SFOS 3.4.0 yet (v3.4.0.24 has been released as "General Availability (GA)" yesterday), but I suspected from its release notes and changelog, that user `nemo` is not member of the group `system` anymore (since SFOS 3.4.0).  So this is a general issue.  Altering the polkit rule is the right thing to do.  As your solution works fine, don't worry.  I will check, if there is an alternative to setting the polkit rule to a *user* or if this is the best solution, when I upgraded one of my devices to SFOS 3.4.0 (likely this weekend).

* WRT systemd-escape: Thank, will correct that.
* WRT lazytime: Oops, thanks!  Will fix that, too.

**Comment by Olf0** [comment]
* systemd-escape moved from /bin to /usr/bin in SFOS 3.4.0 https://github.com/Olf0/crypto-sdcard/commit/704d63c5765e0a4761a6628171c9e9a965dd10e0
* WRT lazytime: See https://github.com/Olf0/crypto-sdcard/commit/5cd9937eb99297584715107148eac67035119400 and https://github.com/Olf0/crypto-sdcard/commit/188e250e1222dde15ad42b15842c95d9c4435244

**Comment by Olf0** [comment]
@fuchsmich, after some analysis, I think 
> I changed the polkit rule to the user `sailfish-system`
meant "changed the polkit rule to the *group* `sailfish-system`" or (equivalent, but simpler) "altered the group from `system` to `sailfish-system` in the polkit rule", right?

Anyway, I did not like the group `sailfish-system`, because it also contains the user `sailfish-mdm`, and the old, but previously (sometime between SFOS 2.2.1 and 3.2.1) unopopulated group `media_rw`, which now contains only the primary user, IMO fits much better (WRT what it is for), anyway.

**Comment by Olf0** [comment]
Hopefully https://github.com/Olf0/crypto-sdcard/releases/tag/1.3.0 and https://github.com/Olf0/crypto-sdcard_sbj/releases/tag/1.3.0 install and work fine on SFOS 3.4.0 (also uploaded to Openrepos).
Can you please check that on your device.

**Comment by Olf0** [comment]
Hopefully https://github.com/Olf0/crypto-sdcard/releases/tag/1.3.0 and https://github.com/Olf0/crypto-sdcard_sbj/releases/tag/1.3.0 install and worrk fine on SFOS 3.4.0 (also uploaded to Openrepos).
Can you please check that on your device.

**Comment by fuchsmich** [comment]
> "altered the group from system to sailfish-system in the polkit rule", right?

Yes, sorry for my gibberish.

**Comment by fuchsmich** [comment]
I guess sth went wrong with the build of 1.3.0. The rpm on openrepos it still contains the `lazytime` option.

**Comment by Olf0** [comment]
Argh, worse than that: I lost track of what I committed to which branches!
"No lazytime" is in the master branch, but I forgot to push that to the sfos340 branch.
Then tagging, packaging and deploying is a straight-forward process.

Sorry, I am in the process of reorganising this github repo's structure, due to the new need of different, OS version dependent releases.  I am not used to the adapted commit processes this requires, yet.

And thanks again for testing.  My only device on SFOS3.4.0 has no SD-card, so I just install-tested.

**Comment by fuchsmich** [comment]
You can count on me with testing, just send me a rpm.

**Comment by Olf0** [comment]
@fuchsmich, please download the [crypto-sdcard-1.3.1-1.sfos340.noarch.rpm](https://github.com/Olf0/crypto-sdcard/releases/tag/1.3.1-1.sfos340) preferably in `/tmp` (e.g. per, `cd /tmp && curl -LO https://github.com/Olf0/crypto-sdcard/releases/download/1.3.1-1.sfos340/crypto-sdcard-1.3.1-1.sfos340.noarch.rpm`) and install it per `devel-su pkcon install-local crypto-sdcard-1.3.1-1.sfos340.noarch.rpm` (or per Storeman, Section "Local RPMs").
Finger crossed, that I did not miss anything this time.

**Comment by fuchsmich** [comment]
The rpm works. sdcard mounts on startup. All fixes are included.

**Comment by Olf0** [comment]
Well, thank you very much @fuchsmich for your analysis and testing.

Unfortunately there are still a few hurdles ahead:
* Let us see, if the correct updates are offered, when I built and uploaded the "qcrypto" variants to Openrepos.  You see them on a different page (https://openrepos.net/content/olf/crypto-sdcard-sbj-edition), but in reality all packages are in the [same repository there](https://openrepos.net/user/5928/programs).  I did some local testing and it looks fine, but a test at Openrepos can only be done by publishing the new RPMs there (hence this is a "live test", unfortunately).
* Jolla's *udisksctl-user* script cannot be forced into unmounting correctly, AFAICS (I tried hard).  I am considering to abandon its use, but then my startup and mounting process for SD-cards (and USB-attached strorage) will differ significantly from Jolla's, making it more likely to be broken by SailfishOS upgrades.  But tackling this is on a longer time scale and needs much pondering and testing.

**Comment by fuchsmich** [comment]
Thanks for your work! 👍 

I'm not sure, if I understand correctly. Every user hase one repo on openrepos, which contains all uploaded programs. Yours is https://sailfish.openrepos.net/olf/

**Comment by Olf0** [comment]
Yes, exactly.

That is why [Bluetooth OBEX Filter off](https://openrepos.net/content/obexdcontentfilterolf/bluetooth-obex-filter) is published by a different [user name](https://openrepos.net/users/obexdcontentfilterolf), because only this way a separate repository at Openrepos is created and used.
